import {defineColorTokens, themedToken} from '../tools/define';

const semanticTokenValues = {
  
  "white": themedToken({ dark: "white.500",
  light: "white.500" }),
  
  "black": themedToken({ dark: "black.500",
  light: "black.500" }),
  
  "header-primary": themedToken({ dark: "primary.130",
  light: "primary.860" }),
  "header-secondary": themedToken({ dark: "primary.330",
  light: "primary.500",
  amoled: "primary.345" }),
  
  "text-normal": themedToken({ dark: "primary.230",
  light: "primary.600",
  amoled: "primary.300" }),
  "text-muted": themedToken({ dark: "primary.360",
  light: "primary.460",
  amoled: "primary.345" }),
  "text-link": themedToken({ dark: "blue.345",
  light: "blue.430" }),
  "text-link-low-saturation": themedToken({ dark: "blue.330",
  light: "blue.430" }),
  "text-positive": themedToken({ dark: "green.330",
  light: "green.430" }),
  "text-warning": themedToken({ dark: "yellow.300",
  light: "yellow.430" }),
  "text-danger": themedToken({ dark: "red.345",
  light: "red.500" }),
  "text-brand": themedToken({ dark: "brand.360",
  light: "brand.500" }),
  
  "interactive-normal": themedToken({ dark: "primary.330",
  light: "primary.500",
  amoled: "primary.345" }),
  "interactive-hover": themedToken({ dark: "primary.230",
  light: "primary.600" }),
  "interactive-active": themedToken({ dark: "white.500",
  light: "primary.860" }),
  "interactive-muted": themedToken({ dark: "primary.500",
  light: "primary.300" }),
  
  "background-primary": themedToken({ dark: "primary.600",
  light: "white.500",
  amoled: "primary.900" }),
  "background-secondary": themedToken({ dark: "primary.630",
  light: "primary.130",
  amoled: "primary.830" }),
  "background-secondary-alt": themedToken({ dark: "primary.660",
  light: "primary.160",
  amoled: "primary.800" }),
  "background-tertiary": themedToken({ dark: "primary.700",
  light: "primary.200",
  amoled: "primary.860" }),
  "background-accent": themedToken({ dark: "primary.530",
  light: "primary.430",
  amoled: "primary.760" }),
  "background-floating": themedToken({ dark: "primary.800",
  light: "white.500",
  amoled: "primary.830" }),
  "background-nested-floating": themedToken({ dark: "primary.630",
  light: "white.500",
  amoled: "primary.830" }),
  
  "home-background": themedToken({ dark: "primary.645",
  light: "primary.100",
  amoled: "primary.760" }),
  
  "background-mobile-primary": themedToken({ dark: "primary.600",
  light: "primary.100",
  amoled: "black.500" }),
  "background-mobile-secondary": themedToken({ dark: "primary.630",
  light: "white.500",
  amoled: "primary.860" }),
  "background-modifier-hover": themedToken({ dark: { color: "primary.500", opacity: 0.3 },
  light: { color: "primary.400", opacity: 0.16 },
  amoled: { color: "primary.560", opacity: 0.4 } }),
  "background-modifier-active": themedToken({ dark: { color: "primary.500", opacity: 0.48 },
  light: { color: "primary.400", opacity: 0.2 },
  amoled: { color: "primary.560", opacity: 0.48 } }),
  "background-modifier-selected": themedToken({ dark: { color: "primary.500", opacity: 0.6 },
  light: { color: "primary.400", opacity: 0.24 },
  amoled: { color: "primary.560", opacity: 0.6 } }),
  "background-modifier-accent": themedToken({ dark: { color: "primary.500", opacity: 0.48 },
  light: { color: "primary.400", opacity: 0.24 },
  amoled: { color: "primary.560", opacity: 0.48 } }),
  "background-mentioned": themedToken({ dark: { color: "yellow.300", opacity: 0.1 },
  light: { color: "yellow.300", opacity: 0.1 } }),
  "background-mentioned-hover": themedToken({ dark: { color: "yellow.300", opacity: 0.08 },
  light: { color: "yellow.300", opacity: 0.2 } }),
  "background-message-hover": themedToken({ dark: { color: "primary.900", opacity: 0.06 },
  light: { color: "primary.900", opacity: 0.03 } }),
  "background-message-automod": themedToken({ dark: { color: "red.400", opacity: 0.05 },
  light: { color: "red.400", opacity: 0.05 } }),
  "background-message-automod-hover": themedToken({ dark: { color: "red.400", opacity: 0.1 },
  light: { color: "red.400", opacity: 0.1 } }),
  "background-message-highlight": themedToken({ dark: { color: "brand.360", opacity: 0.08 },
  light: { color: "brand.360", opacity: 0.1 } }),
  "background-message-highlight-hover": themedToken({ dark: { color: "brand.360", opacity: 0.06 },
  light: { color: "brand.360", opacity: 0.2 } }),
  
  "status-positive-background": themedToken({ dark: "green.430",
  light: "green.430" }),
  "status-positive-text": themedToken({ dark: "white.500",
  light: "white.500" }),
  "status-warning-background": themedToken({ dark: "yellow.300",
  light: "yellow.400" }),
  "status-warning-text": themedToken({ dark: "black.500",
  light: "white.500" }),
  "status-danger-background": themedToken({ dark: "red.400",
  light: "red.430" }),
  "status-danger-text": themedToken({ dark: "white.500",
  light: "white.500" }),
  "status-danger": themedToken({ dark: "red.400",
  light: "red.430" }),
  "status-positive": themedToken({ dark: "green.360",
  light: "green.400" }),
  "status-warning": themedToken({ dark: "yellow.300",
  light: "yellow.400" }),
  
  "border-subtle": themedToken({ dark: { color: "white.500", opacity: 0.08 },
  light: { color: "black.500", opacity: 0.08 } }),
  "border-strong": themedToken({ dark: { color: "white.500", opacity: 0.16 },
  light: { color: "black.500", opacity: 0.16 } }),
  
  "divider-subtle": themedToken({ dark: { color: "white.500", opacity: 0.08 },
  light: { color: "black.500", opacity: 0.08 } }),
  "divider-strong": themedToken({ dark: { color: "white.500", opacity: 0.16 },
  light: { color: "black.500", opacity: 0.16 } }),
  
  "channels-default": themedToken({ dark: "primary.360",
  light: "primary.460" }),
  
  "channel-icon": themedToken({ dark: "primary.400",
  light: "primary.430" }),
  
  "chat-background": themedToken({ dark: "primary.600",
  light: "white.500",
  amoled: "black.500" }),
  "chat-border": themedToken({ dark: "primary.700",
  light: "primary.200" }),
  "chat-input-container-background": themedToken({ dark: "primary.600",
  light: "white.500" }),
  
  "textbox-markdown-syntax": themedToken({ dark: "primary.360",
  light: "primary.530" }),
  
  "spoiler-revealed-background": themedToken({ dark: "primary.660",
  light: "primary.160" }),
  "spoiler-hidden-background": themedToken({ dark: "primary.700",
  light: "primary.200" }),
  
  "mention-foreground": themedToken({ dark: "brand.260",
  light: "brand.500" }),
  "mention-background": themedToken({ dark: { color: "brand.500", opacity: 0.3 },
  light: { color: "brand.500", opacity: 0.15 } }),
  
  "control-brand-foreground": themedToken({ dark: "brand.360",
  light: "brand.500" }),
  "control-brand-foreground-new": themedToken({ dark: "brand.360",
  light: "brand.500" }),
  
  "deprecated-card-bg": themedToken({ dark: { color: "primary.700", opacity: 0.6 },
  light: "primary.100" }),
  "deprecated-card-editable-bg": themedToken({ dark: { color: "primary.700", opacity: 0.3 },
  light: { color: "primary.100", opacity: 0.6 } }),
  "deprecated-store-bg": themedToken({ dark: "primary.600",
  light: "primary.100" }),
  "deprecated-quickswitcher-input-background": themedToken({ dark: "primary.400",
  light: "white.500" }),
  "deprecated-quickswitcher-input-placeholder": themedToken({ dark: { color: "white.500", opacity: 0.3 },
  light: { color: "primary.500", opacity: 0.3 } }),
  "deprecated-text-input-bg": themedToken({ dark: "primary.700",
  light: "primary.200" }),
  "deprecated-text-input-border": themedToken({ dark: { color: "black.500", opacity: 0.3 },
  light: { color: "primary.500", opacity: 0.3 } }),
  "deprecated-text-input-border-hover": themedToken({ dark: "primary.900",
  light: "primary.300" }),
  "deprecated-text-input-border-disabled": themedToken({ dark: "primary.700",
  light: "primary.200" }),
  "deprecated-text-input-prefix": themedToken({ dark: "primary.200",
  light: "primary.300" }),
  
  "button-danger-background": themedToken({ dark: "red.430",
  light: "red.430" }),
  "button-danger-background-hover": themedToken({ dark: "red.500",
  light: "red.500" }),
  "button-danger-background-active": themedToken({ dark: "red.530",
  light: "red.530" }),
  "button-danger-background-disabled": themedToken({ dark: "red.430",
  light: "red.430" }),
  "button-positive-background": themedToken({ dark: "green.430",
  light: "green.430" }),
  "button-positive-background-hover": themedToken({ dark: "green.500",
  light: "green.530",
  amoled: "green.530" }),
  "button-positive-background-active": themedToken({ dark: "green.530",
  light: "green.530" }),
  "button-positive-background-disabled": themedToken({ dark: "green.430",
  light: "green.430" }),
  "button-secondary-background": themedToken({ dark: "primary.500",
  light: "primary.430" }),
  "button-secondary-background-hover": themedToken({ dark: "primary.430",
  light: "primary.500" }),
  "button-secondary-background-active": themedToken({ dark: "primary.400",
  light: "primary.530" }),
  "button-secondary-background-disabled": themedToken({ dark: "primary.500",
  light: "primary.430" }),
  "button-outline-danger-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "button-outline-danger-border": themedToken({ dark: "red.400",
  light: "red.430" }),
  "button-outline-danger-background": themedToken({ dark: { color: "white.500", opacity: 0 },
  light: { color: "white.500", opacity: 0 } }),
  "button-outline-danger-background-hover": themedToken({ dark: "red.430",
  light: "red.430" }),
  "button-outline-danger-text-hover": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-danger-border-hover": themedToken({ dark: "red.430",
  light: "red.430" }),
  "button-outline-danger-background-active": themedToken({ dark: "red.460",
  light: "red.460" }),
  "button-outline-danger-text-active": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-danger-border-active": themedToken({ dark: "red.430",
  light: "red.430" }),
  "button-outline-positive-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "button-outline-positive-border": themedToken({ dark: "green.360",
  light: "green.400" }),
  "button-outline-positive-background": themedToken({ dark: { color: "white.500", opacity: 0 },
  light: { color: "white.500", opacity: 0 } }),
  "button-outline-positive-background-hover": themedToken({ dark: "green.430",
  light: "green.430" }),
  "button-outline-positive-text-hover": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-positive-border-hover": themedToken({ dark: "green.430",
  light: "green.430" }),
  "button-outline-positive-background-active": themedToken({ dark: "green.530",
  light: "green.530" }),
  "button-outline-positive-text-active": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-positive-border-active": themedToken({ dark: "green.530",
  light: "green.530" }),
  "button-outline-brand-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "button-outline-brand-border": themedToken({ dark: "brand.500",
  light: "brand.500" }),
  "button-outline-brand-background": themedToken({ dark: { color: "white.500", opacity: 0 },
  light: { color: "white.500", opacity: 0 } }),
  "button-outline-brand-background-hover": themedToken({ dark: "brand.500",
  light: "brand.500" }),
  "button-outline-brand-text-hover": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-brand-border-hover": themedToken({ dark: "brand.500",
  light: "brand.500" }),
  "button-outline-brand-background-active": themedToken({ dark: "brand.560",
  light: "brand.560" }),
  "button-outline-brand-text-active": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-brand-border-active": themedToken({ dark: "brand.560",
  light: "brand.560" }),
  "button-outline-primary-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "button-outline-primary-border": themedToken({ dark: "primary.500",
  light: "primary.530" }),
  "button-outline-primary-background": themedToken({ dark: { color: "white.500", opacity: 0 },
  light: { color: "white.500", opacity: 0 } }),
  "button-outline-primary-background-hover": themedToken({ dark: "primary.500",
  light: "primary.530" }),
  "button-outline-primary-text-hover": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-primary-border-hover": themedToken({ dark: "primary.500",
  light: "primary.530" }),
  "button-outline-primary-background-active": themedToken({ dark: "primary.430",
  light: "primary.600" }),
  "button-outline-primary-text-active": themedToken({ dark: "white.500",
  light: "white.500" }),
  "button-outline-primary-border-active": themedToken({ dark: "primary.430",
  light: "primary.600" }),
  
  "redesign-button-primary-background": themedToken({ dark: "brand.500",
  light: "brand.500" }),
  "redesign-button-primary-pressed-background": themedToken({ dark: "brand.600",
  light: "brand.600" }),
  "redesign-button-secondary-border": themedToken({ dark: { color: "white.500", opacity: 0.2 },
  light: { color: "black.500", opacity: 0.08 } }),
  "redesign-button-secondary-pressed-background": themedToken({ dark: "primary.700",
  light: "primary.230" }),
  "redesign-button-danger-background": themedToken({ dark: "red.430",
  light: "red.430" }),
  "redesign-button-danger-pressed-background": themedToken({ dark: "red.500",
  light: "red.500" }),
  "redesign-button-positive-background": themedToken({ dark: "green.430",
  light: "green.430" }),
  "redesign-button-positive-pressed-background": themedToken({ dark: "green.500",
  light: "green.500" }),
  "redesign-button-floating-background": themedToken({ dark: "white.500",
  light: "white.500" }),
  "redesign-button-floating-pressed-background": themedToken({ dark: "primary.730",
  light: "primary.730" }),
  
  "input-background": themedToken({ dark: "primary.700",
  light: "primary.200" }),
  "input-placeholder-text": themedToken({ dark: "input-placeholder-text-dark",
  light: "primary.560" }),
  
  "info-positive-background": themedToken({ dark: { color: "green.360", opacity: 0.1 },
  light: { color: "green.400", opacity: 0.05 } }),
  "info-positive-foreground": themedToken({ dark: "green.360",
  light: "green.400" }),
  "info-positive-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "info-warning-background": themedToken({ dark: { color: "yellow.300", opacity: 0.1 },
  light: { color: "yellow.400", opacity: 0.1 } }),
  "info-warning-foreground": themedToken({ dark: "yellow.300",
  light: "yellow.400" }),
  "info-warning-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "info-danger-background": themedToken({ dark: { color: "red.400", opacity: 0.1 },
  light: { color: "red.430", opacity: 0.1 } }),
  "info-danger-foreground": themedToken({ dark: "red.400",
  light: "red.430" }),
  "info-danger-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  "info-help-background": themedToken({ dark: { color: "blue.345", opacity: 0.1 },
  light: { color: "blue.430", opacity: 0.1 } }),
  "info-help-foreground": themedToken({ dark: "blue.345",
  light: "blue.430" }),
  "info-help-text": themedToken({ dark: "white.500",
  light: "black.500" }),
  
  "channel-text-area-placeholder": themedToken({ dark: "primary.430",
  light: "primary.400",
  amoled: "primary.400" }),
  
  "channeltextarea-background": themedToken({ dark: "primary.560",
  light: "primary.160",
  amoled: "primary.800" }),
  
  "activity-card-background": themedToken({ dark: "primary.700",
  light: "white.500" }),
  
  "logo-primary": themedToken({ dark: "white.500",
  light: "brand.500" }),
  
  "focus-primary": themedToken({ dark: "blue.345",
  light: "blue.345" }),
  
  "android-navigation-scrim-background": themedToken({ dark: { color: "primary.830", opacity: 0.5 },
  light: { color: "primary.100", opacity: 0.5 } }),
  
  "bug-reporter-modal-submitting-background": themedToken({ dark: { color: "primary.800", opacity: 0.6 },
  light: { color: "white.500", opacity: 0.6 } }),
  
  "forum-post-extra-media-count-container-background": themedToken({ dark: { color: "primary.660", opacity: 0.8 },
  light: { color: "primary.160", opacity: 0.8 } }),
  "forum-post-tag-background": themedToken({ dark: { color: "primary.660", opacity: 0.9 },
  light: { color: "primary.160", opacity: 0.9 } }),
  
  "live-stage-tile-border": themedToken({ dark: { color: "primary.500", opacity: 0.6 },
  light: { color: "primary.430", opacity: 0.15 } }),
  
  "user-profile-header-overflow-background": themedToken({ dark: { color: "primary.700", opacity: 0.5 },
  light: { color: "white.200", opacity: 0.5 } }),
  
  "display-banner-overflow-background": themedToken({ dark: { color: "primary.700", opacity: 0.5 },
  light: { color: "white.200", opacity: 0.5 } }),
  
  "info-box-background": themedToken({ dark: { color: "blue.345", opacity: 0.1 },
  light: { color: "blue.345", opacity: 0.1 } }),
  
  "home-card-resting-border": themedToken({ dark: "transparent",
  light: { color: "primary.400", opacity: 0.24 } }),
  
  "android-navigation-bar-background": themedToken({ dark: "primary.830",
  light: "primary.100" }),
  "android-ripple": themedToken({ dark: { color: "white.500", opacity: 0.07 },
  light: { color: "black.500", opacity: 0.12 } }),
  
  "modal-background": themedToken({ dark: "primary.600",
  light: "white.500" }),
  "modal-footer-background": themedToken({ dark: "primary.630",
  light: "primary.130" }),
  
  "profile-gradient-overlay-synced-with-user-theme": themedToken({ dark: { color: "black.500", opacity: 0.8 },
  light: { color: "white.500", opacity: 0.8 } }),
  "profile-gradient-overlay": themedToken({ dark: { color: "black.500", opacity: 0.6 },
  light: { color: "white.500", opacity: 0.6 } }),
  "profile-gradient-section-box": themedToken({ dark: { color: "black.500", opacity: 0.45 },
  light: { color: "white.500", opacity: 0.45 } }),
  "profile-gradient-message-input-border": themedToken({ dark: { color: "primary.500", opacity: 0.48 },
  light: { color: "primary.430", opacity: 0.24 } }),
  "profile-gradient-note-background": themedToken({ dark: { color: "black.500", opacity: 0.3 },
  light: { color: "white.500", opacity: 0.3 } }),
  "profile-gradient-profile-body-background-hover": themedToken({ dark: { color: "white.500", opacity: 0.16 },
  light: { color: "black.500", opacity: 0.08 } }),
  "profile-gradient-role-pill-background": themedToken({ dark: { color: "primary.660", opacity: 0.5 },
  light: { color: "white.500", opacity: 0.5 } }),
  "profile-gradient-role-pill-border": themedToken({ dark: { color: "white.500", opacity: 0.2 },
  light: { color: "primary.660", opacity: 0.2 } }),
  
  "scrollbar-thin-thumb": themedToken({ dark: "primary.730",
  light: { color: "primary.500", opacity: 0.3 },
  amoled: "primary.700" }),
  "scrollbar-thin-track": themedToken({ dark: { color: "black.500", opacity: 0 },
  light: { color: "black.500", opacity: 0 } }),
  "scrollbar-auto-thumb": themedToken({ dark: "primary.730",
  light: "primary.300",
  amoled: "primary.600" }),
  "scrollbar-auto-track": themedToken({ dark: "primary.630",
  light: "primary.160",
  amoled: "primary.860" }),
  "scrollbar-auto-scrollbar-color-thumb": themedToken({ dark: "primary.730",
  light: "primary.230",
  amoled: "primary.700" }),
  "scrollbar-auto-scrollbar-color-track": themedToken({ dark: "primary.630",
  light: "primary.130" })
};

export const semanticTokens = defineColorTokens(() => semanticTokenValues);
export type SemanticTokenValue = typeof semanticTokenValues;